export const rows = [
  {
    id: 1,
    TitreDuTicket: "2023-01-01",
    region: "Nord",
    province: "Province1",
    unite: "Unité1",
    probleme: "CAMERA SURVILLANCE",
    cause: "Problème logiciel",
    type: "Type1",
    categorie: "Catégorie1",
    priorite: "High",
    remontePar: "MEDECIN",
    ouvertLe: "2023-01-01",
    fermeLe: "2023-01-02",
    supportTech: "Support1",
    besoin: "Besoin1",
    remarques: "Remarques1",
    action: "action",
  },
  {
    id: 2,
    TitreDuTicket: "2023-02-01",
    region: "Sud",
    province: "Province2",
    unite: "Unité2",
    probleme: "RESEAU",
    cause: "Problème matériel",
    type: "Type2",
    categorie: "Catégorie2",
    priorite: "Medium",
    remontePar: "INFIRMIER",
    ouvertLe: "2023-02-01",
    fermeLe: "2023-02-03",
    supportTech: "Support2",
    besoin: "Besoin2",
    remarques: "Remarques2",
  },
  {
    id: 3,
    TitreDuTicket: "2023-03-01",
    region: "Est",
    province: "Province3",
    unite: "Unité3",
    probleme: "ELECTRICITE",
    cause: "Problème réseau",
    type: "Type3",
    categorie: "Catégorie3",
    priorite: "Low",
    remontePar: "TECHNICIEN",
    ouvertLe: "2023-03-01",
    fermeLe: "2023-03-04",
    supportTech: "Support3",
    besoin: "Besoin3",
    remarques: "Remarques3",
  },
  {
    id: 4,
    TitreDuTicket: "2023-04-01",
    region: "Ouest",
    province: "Province4",
    unite: "Unité4",
    probleme: "CLIMATISATION",
    cause: "Problème mécanique",
    type: "Type4",
    categorie: "Catégorie4",
    priorite: "High",
    remontePar: "MEDECIN",
    ouvertLe: "2023-04-01",
    fermeLe: "2023-04-05",
    supportTech: "Support4",
    besoin: "Besoin4",
    remarques: "Remarques4",
  },
  {
    id: 5,
    TitreDuTicket: "2023-05-01",
    region: "Nord",
    province: "Province5",
    unite: "Unité5",
    probleme: "CAMERA SURVILLANCE",
    cause: "Problème logiciel",
    type: "Type1",
    categorie: "Catégorie1",
    priorite: "High",
    remontePar: "MEDECIN",
    ouvertLe: "2023-05-01",
    fermeLe: "2023-05-02",
    supportTech: "Support5",
    besoin: "Besoin5",
    remarques: "Remarques5",
  },
  {
    id: 6,
    TitreDuTicket: "2023-06-01",
    region: "Sud",
    province: "Province6",
    unite: "Unité6",
    probleme: "RESEAU",
    cause: "Problème matériel",
    type: "Type2",
    categorie: "Catégorie2",
    priorite: "Medium",
    remontePar: "INFIRMIER",
    ouvertLe: "2023-06-01",
    fermeLe: "2023-06-03",
    supportTech: "Support6",
    besoin: "Besoin6",
    remarques: "Remarques6",
  },
  {
    id: 7,
    TitreDuTicket: "2023-07-01",
    region: "Est",
    province: "Province7",
    unite: "Unité7",
    probleme: "ELECTRICITE",
    cause: "Problème réseau",
    type: "Type3",
    categorie: "Catégorie3",
    priorite: "Low",
    remontePar: "TECHNICIEN",
    ouvertLe: "2023-07-01",
    fermeLe: "2023-07-04",
    supportTech: "Support7",
    besoin: "Besoin7",
    remarques: "Remarques7",
  },
  {
    id: 8,
    TitreDuTicket: "2023-08-01",
    region: "Ouest",
    province: "Province8",
    unite: "Unité8",
    probleme: "CLIMATISATION",
    cause: "Problème mécanique",
    type: "Type4",
    categorie: "Catégorie4",
    priorite: "High",
    remontePar: "MEDECIN",
    ouvertLe: "2023-08-01",
    fermeLe: "2023-08-05",
    supportTech: "Support8",
    besoin: "Besoin8",
    remarques: "Remarques8",
  },
  {
    id: 9,
    TitreDuTicket: "2023-09-01",
    region: "Nord",
    province: "Province9",
    unite: "Unité9",
    probleme: "CAMERA SURVILLANCE",
    cause: "Problème logiciel",
    type: "Type1",
    categorie: "Catégorie1",
    priorite: "High",
    remontePar: "MEDECIN",
    ouvertLe: "2023-09-01",
    fermeLe: "2023-09-02",
    supportTech: "Support9",
    besoin: "Besoin9",
    remarques: "Remarques9",
  },
  {
    id: 10,
    TitreDuTicket: "2023-10-01",
    region: "Sud",
    province: "Province10",
    unite: "Unité10",
    probleme: "RESEAU",
    cause: "Problème matériel",
    type: "Type2",
    categorie: "Catégorie2",
    priorite: "Medium",
    remontePar: "INFIRMIER",
    ouvertLe: "2023-10-01",
    fermeLe: "2023-10-03",
    supportTech: "Support10",
    besoin: "Besoin10",
    remarques: "Remarques10",
  },
  {
    id: 11,
    TitreDuTicket: "2023-11-01",
    region: "Est",
    province: "Province11",
    unite: "Unité11",
    probleme: "ELECTRICITE",
    cause: "Problème réseau",
    type: "Type3",
    categorie: "Catégorie3",
    priorite: "Low",
    remontePar: "TECHNICIEN",
    ouvertLe: "2023-11-01",
    fermeLe: "2023-11-04",
    supportTech: "Support11",
    besoin: "Besoin11",
    remarques: "Remarques11",
  },
  {
    id: 12,
    TitreDuTicket: "2023-12-01",
    region: "Ouest",
    province: "Province12",
    unite: "Unité12",
    probleme: "CLIMATISATION",
    cause: "Problème mécanique",
    type: "Type4",
    categorie: "Catégorie4",
    priorite: "High",
    remontePar: "MEDECIN",
    ouvertLe: "2023-12-01",
    fermeLe: "2023-12-05",
    supportTech: "Support12",
    besoin: "Besoin12",
    remarques: "Remarques12",
  },
  {
    id: 13,
    TitreDuTicket: "2024-01-01",
    region: "Nord",
    province: "Province13",
    unite: "Unité13",
    probleme: "CAMERA SURVILLANCE",
    cause: "Problème logiciel",
    type: "Type1",
    categorie: "Catégorie1",
    priorite: "High",
    remontePar: "MEDECIN",
    ouvertLe: "2024-01-01",
    fermeLe: "2024-01-02",
    supportTech: "Support13",
    besoin: "Besoin13",
    remarques: "Remarques13",
  },
  {
    id: 14,
    TitreDuTicket: "2024-02-01",
    region: "Sud",
    province: "Province14",
    unite: "Unité14",
    probleme: "RESEAU",
    cause: "Problème matériel",
    type: "Type2",
    categorie: "Catégorie2",
    priorite: "Medium",
    remontePar: "INFIRMIER",
    ouvertLe: "2024-02-01",
    fermeLe: "2024-02-03",
    supportTech: "Support14",
    besoin: "Besoin14",
    remarques: "Remarques14",
  },
];
