export const rows = [
  {
    id: 1,
    col1: "UMMC OUMEJRANE TINGHIR",
    col2: "Drâa-Tafilalet",
    col3: "Tinghir",
    col4: "LALLALEN Oumaima",
    col5: "ANNOUN Anass",
    col6: "omar omar",
    col7: "DR CHAACHOUE",
    col8: "UMMC_OUMEJRANE@mediot.io",
    col9: "06-61-00-11-22",
    col10: "📍",
  },
  {
    id: 2,
    col1: "UMMC ERFOUD",
    col2: "Drâa-Tafilalet",
    col3: "Errachidia",
    col4: "BOUSSAID Khalid",
    col5: "EL HASSAN Soufiane",
    col6: "mohamed mohamed",
    col7: "DR AIT BASSOU",
    col8: "UMMC_ERFOUD@mediot.io",
    col9: "06-61-00-11-23",
    col10: "📍",
  },
  {
    id: 3,
    col1: "UMMC ZAGORA",
    col2: "Drâa-Tafilalet",
    col3: "Zagora",
    col4: "HAMMOUDA Nezha",
    col5: "AHMED Said",
    col6: "youssef youssef",
    col7: "DR EL MOKHTAR",
    col8: "UMMC_ZAGORA@mediot.io",
    col9: "06-61-00-11-24",
    col10: "📍",
  },
  {
    id: 4,
    col1: "UMMC OUARZAZATE",
    col2: "Drâa-Tafilalet",
    col3: "Ouarzazate",
    col4: "FARAH Noura",
    col5: "KHALID Younes",
    col6: "ismail ismail",
    col7: "DR BOUCHAIB",
    col8: "UMMC_OUARZAZATE@mediot.io",
    col9: "06-61-00-11-25",
    col10: "📍",
  },
  {
    id: 5,
    col1: "UMMC MIDELT",
    col2: "Drâa-Tafilalet",
    col3: "Midelt",
    col4: "RAJAA Fatima",
    col5: "HICHAM Omar",
    col6: "rachid rachid",
    col7: "DR KHADIJA",
    col8: "UMMC_MIDELT@mediot.io",
    col9: "06-61-00-11-26",
    col10: "📍",
  },
  {
    id: 6,
    col1: "UMMC TINGHIR CENTRE",
    col2: "Drâa-Tafilalet",
    col3: "Tinghir",
    col4: "LAMRINI Hajar",
    col5: "MOHAMED Ali",
    col6: "karim karim",
    col7: "DR AZIZ",
    col8: "UMMC_TINGHIR_CENTRE@mediot.io",
    col9: "06-61-00-11-27",
    col10: "📍",
  },
  {
    id: 7,
    col1: "UMMC RISSANI",
    col2: "Drâa-Tafilalet",
    col3: "Errachidia",
    col4: "YASSIR Malika",
    col5: "SAID Hamid",
    col6: "younes younes",
    col7: "DR RACHID",
    col8: "UMMC_RISSANI@mediot.io",
    col9: "06-61-00-11-28",
    col10: "📍",
  },
  {
    id: 8,
    col1: "UMMC ALNIF",
    col2: "Drâa-Tafilalet",
    col3: "Tinghir",
    col4: "LATIFA Leila",
    col5: "HASSAN Mohamed",
    col6: "omar omar",
    col7: "DR ABDEL",
    col8: "UMMC_ALNIF@mediot.io",
    col9: "06-61-00-11-29",
    col10: "📍",
  },
  {
    id: 9,
    col1: "UMMC BOUMALNE",
    col2: "Drâa-Tafilalet",
    col3: "Tinghir",
    col4: "FATIMA Zahra",
    col5: "YOUSSEF Rachid",
    col6: "hamza hamza",
    col7: "DR AMINA",
    col8: "UMMC_BOUMALNE@mediot.io",
    col9: "06-61-00-11-30",
    col10: "📍",
  },
  {
    id: 10,
    col1: "UMMC SKOURA",
    col2: "Drâa-Tafilalet",
    col3: "Ouarzazate",
    col4: "EL AMRI Latifa",
    col5: "NAJIB Ahmed",
    col6: "ahmed ahmed",
    col7: "DR MOHAMED",
    col8: "UMMC_SKOURA@mediot.io",
    col9: "06-61-00-11-31",
    col10: "📍",
  },
  {
    id: 11,
    col1: "UMMC ERRACHIDIA CENTRE",
    col2: "Drâa-Tafilalet",
    col3: "Errachidia",
    col4: "SOUAD Amina",
    col5: "OMAR Youssef",
    col6: "khalid khalid",
    col7: "DR TAREK",
    col8: "UMMC_ERRACHIDIA_CENTRE@mediot.io",
    col9: "06-61-00-11-32",
    col10: "📍",
  },
  {
    id: 12,
    col1: "UMMC TINEJDAD",
    col2: "Drâa-Tafilalet",
    col3: "Tinghir",
    col4: "HASSANI Aicha",
    col5: "HAMID Younes",
    col6: "omar omar",
    col7: "DR AHMED",
    col8: "UMMC_TINEJDAD@mediot.io",
    col9: "06-61-00-11-33",
    col10: "📍",
  },
  {
    id: 13,
    col1: "UMMC MHAMID EL GHIZLANE",
    col2: "Drâa-Tafilalet",
    col3: "Zagora",
    col4: "SAIDA Fatima",
    col5: "MOHAMED Rachid",
    col6: "hamid hamid",
    col7: "DR KHALIL",
    col8: "UMMC_MHAMID_EL_GHIZLANE@mediot.io",
    col9: "06-61-00-11-34",
    col10: "📍",
  },
  {
    id: 14,
    col1: "UMMC GHRISS",
    col2: "Drâa-Tafilalet",
    col3: "Errachidia",
    col4: "FADWA Loubna",
    col5: "SAID Hamza",
    col6: "youssef youssef",
    col7: "DR MOHAMED",
    col8: "UMMC_GHRISS@mediot.io",
    col9: "06-61-00-11-35",
    col10: "📍",
  },
  {
    id: 15,
    col1: "UMMC TAZZARINE",
    col2: "Drâa-Tafilalet",
    col3: "Zagora",
    col4: "NAJAT Naima",
    col5: "HAMID Said",
    col6: "omar omar",
    col7: "DR TAREK",
    col8: "UMMC_TAZZARINE@mediot.io",
    col9: "06-61-00-11-36",
    col10: "📍",
  },
  {
    id: 16,
    col1: "UMMC TINGHIR NORD",
    col2: "Drâa-Tafilalet",
    col3: "Tinghir",
    col4: "NAIMA Najat",
    col5: "HASSAN Mohamed",
    col6: "rachid rachid",
    col7: "DR OMAR",
    col8: "UMMC_TINGHIR_NORD@mediot.io",
    col9: "06-61-00-11-37",
    col10: "📍",
  },
  {
    id: 17,
    col1: "UMMC BOUMALNE DADES",
    col2: "Drâa-Tafilalet",
    col3: "Tinghir",
    col4: "HIND Zahra",
    col5: "SAID Youssef",
    col6: "younes younes",
    col7: "DR AHMED",
    col8: "UMMC_BOUMALNE_DADES@mediot.io",
    col9: "06-61-00-11-38",
    col10: "📍",
  },
  {
    id: 18,
    col1: "UMMC TINERHIR",
    col2: "Drâa-Tafilalet",
    col3: "Tinghir",
    col4: "LAILA Naima",
    col5: "HASSAN Khalid",
    col6: "omar omar",
    col7: "DR SAID",
    col8: "UMMC_TINERHIR@mediot.io",
    col9: "06-61-00-11-39",
    col10: "📍",
  },
  {
    id: 19,
    col1: "UMMC AGDZ",
    col2: "Drâa-Tafilalet",
    col3: "Zagora",
    col4: "ZAHRA Hind",
    col5: "HAMZA Said",
    col6: "youssef youssef",
    col7: "DR OMAR",
    col8: "UMMC_AGDZ@mediot.io",
    col9: "06-61-00-11-40",
    col10: "📍",
  },
  {
    id: 20,
    col1: "UMMC KHENIFRA",
    col2: "Drâa-Tafilalet",
    col3: "Khenifra",
    col4: "AYOUB Laila",
    col5: "OMAR Younes",
    col6: "karim karim",
    col7: "DR AMINA",
    col8: "UMMC_KHENIFRA@mediot.io",
    col9: "06-61-00-11-41",
    col10: "📍",
  },
];

export const columns = [
  {
    field: "id",
    headerName: "ID",
    align: "center",
    flex: 1,
    headerAlign: "center",
  },
  {
    field: "col1",
    headerName: "Nom",
    align: "center",
    flex: 1,
    headerAlign: "center",
  },
  {
    field: "col2",
    headerName: "Région",
    align: "center",
    flex: 1,
    headerAlign: "center",
  },
  {
    field: "col3",
    headerName: "Province",
    align: "center",
    flex: 1,
    headerAlign: "center",
  },
  {
    field: "col4",
    headerName: "Coordinateur",
    align: "center",
    flex: 1,
    headerAlign: "center",
  },
  {
    field: "col5",
    headerName: "Chargé de suivi",
    align: "center",
    flex: 1,
    headerAlign: "center",
  },
  {
    field: "col6",
    headerName: "Technicien",
    align: "center",
    flex: 1,
    headerAlign: "center",
  },
  {
    field: "col7",
    headerName: "Doctor",
    align: "center",
    flex: 1,
    headerAlign: "center",
  },
  {
    field: "col8",
    headerName: "E-mail",
    align: "center",
    flex: 2,
    headerAlign: "center",
  },
  {
    field: "col9",
    headerName: "Phone",
    align: "center",
    flex: 1,
    headerAlign: "center",
  },
  {
    field: "col10",
    headerName: "Position",
    align: "center",
    flex: 1,
    headerAlign: "center",
  },
];
